.DELETE_ON_ERROR:
.PHONY: all bin valgrind check test docker dockerbuild debsrc debbin clean
.DEFAULT_GOAL:=all

VERSION:=0.0.3~pre

SRC:=src
OUT:=.out
TAGS:=.tags
BINOUT:=$(OUT)
BIN:=$(BINOUT)/catena
TESTBIN:=$(BINOUT)/catenatest
VALGRIND:=valgrind --tool=memcheck --leak-check=full

HTTPDLIBS:=$(shell pkg-config --libs libmicrohttpd)
HTTPDCFLAGS:=$(shell pkg-config --cflags libmicrohttpd)
SSLLIBS:=$(shell pkg-config --libs openssl)
SSLCFLAGS:=$(shell pkg-config --cflags openssl)
READLINELIBS:=-lreadline

CPPSRCDIRS:=$(wildcard $(SRC)/*)
CPPSRC:=$(shell find $(CPPSRCDIRS) -type f -iname \*.cpp -print)
CPPINC:=$(shell find $(CPPSRCDIRS) -type f -iname \*.h -print)
VERSIONH:=$(OUT)/version.h # generated by Makefile

CATENASRC:=$(foreach dir, $(SRC)/catena $(SRC)/libcatena, $(filter $(dir)/%, $(CPPSRC)))
CATENAOBJ:=$(addprefix $(OUT)/, $(CATENASRC:%.cpp=%.o))
CATENAINC:=$(foreach dir, $(SRC)/catena $(SRC)/libcatena, $(filter $(dir)/%, $(CPPINC)))
CATENATESTSRC:=$(foreach dir, $(SRC)/test $(SRC)/libcatena, $(filter $(dir)/%, $(CPPSRC)))
CATENATESTOBJ:=$(addprefix $(OUT)/, $(CATENATESTSRC:%.cpp=%.o))
CATENATESTINC:=$(foreach dir, $(SRC)/test $(SRC)/libcatena, $(filter $(dir)/%, $(CPPINC)))
# libcatena is not its own binary, just a namespace; no src/obj rules necessary
LIBCATENAINC:=$(foreach dir, $(SRC)/libcatena, $(filter $(dir)/%, $(CPPINC)))

LEDGER:=genesisblock
TESTDATA:=$(wildcard test/*) $(LEDGER)
DOCKERFILE:=Dockerfile
DOCKERBUILDFILE:=doc/Dockerfile.build

WFLAGS:=-Wall -W -Werror -Werror=vla
# clang doesn't like this
# WFLAGS+=-Wl,-z,defs
OFLAGS:=-g -O2
CPPFLAGS:=-I$(SRC)
CXXFLAGS:=-pipe -std=c++17 -pthread
EXTCPPFLAGS:=$(SSLCFLAGS) $(HTTPDCFLAGS)
CXXFLAGS:=$(CXXFLAGS) $(WFLAGS) $(OFLAGS) $(CPPFLAGS) $(EXTCPPFLAGS)

# FIXME detect this, or let it be specified
LDLIBSGTEST:=/usr/lib/x86_64-linux-gnu/libgtest.a

all: $(TAGS) $(BIN) $(TESTBIN)

$(BINOUT)/catena: $(CATENAOBJ)
	@mkdir -p $(@D)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(SSLLIBS) $(HTTPDLIBS) $(READLINELIBS)

$(BINOUT)/catenatest: $(CATENATESTOBJ)
	@mkdir -p $(@D)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDLIBSGTEST) $(SSLLIBS)

$(OUT)/$(SRC)/catena/%.o: $(SRC)/catena/%.cpp $(CATENAINC) $(VERSIONH)
	@mkdir -p $(@D)
	$(CXX) -include $(VERSIONH) $(CXXFLAGS) -c $< -o $@

$(OUT)/$(SRC)/test/%.o: $(SRC)/test/%.cpp $(CATENATESTINC)
	@mkdir -p $(@D)
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(OUT)/$(SRC)/libcatena/%.o: $(SRC)/libcatena/%.cpp $(LIBCATENAINC)
	@mkdir -p $(@D)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Generated targets which live outside of $(OUT)
$(TAGS): $(CPPSRC) $(CPPINC)
	ctags -f $@ $^ || true

bin: $(BIN)

check: test

$(VERSIONH): $(MAKEFILE_LIST)
	@mkdir -p $(@D)
	echo "#ifndef CATENA_CATENA_VERSION\n#define CATENA_CATENA_VERSION\nnamespace CatenaAgent{constexpr const char VERSION[] = \"$(VERSION)\";}\n#endif" > $@

test: $(TAGS) $(TESTBIN) $(TESTDATA)
	$(BINOUT)/catenatest

valgrind: $(TAGS) $(TESTBIN) $(TESTDATA)
	$(VALGRIND) $(BINOUT)/catenatest

DOCKEROUT:=$(OUT)/dockerbuilt
# FIXME need to dep on .deb from dockerbuild target
docker: $(DOCKERFILE)
	docker build -f $< $(DOCKEROUT)

dockerbuild: $(DOCKERBUILDFILE)
	docker build -f $< .
	# need to get container from above with -q
	@mkdir -p $(DOCKEROUT)/
	# need to get source packages FIXME
	docker cp $(CONTAINER):catena/*deb $(DOCKEROUT)

debsrc:
	dpkg-source --build .

debbin: debsrc
	@mkdir -p $(OUT)/deb
	sudo pbuilder build --buildresult $(OUT)/deb ../*dsc

clean:
	rm -rf $(OUT) $(TAGS)
