FROM debian:buster
RUN apt-get update
RUN apt-get install --assume-yes --no-install-recommends \
  libreadline7 libmicrohttpd12 libssl1.1 libcapnp-0.7.0 libgtest-dev

EXPOSE 8080 40404

# Send requisite building materials to $WORKDIR
COPY .out/deb/* /tmp/

RUN dpkg -i /tmp/*deb
